name: Vérification du respect des spécifications

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Cache pip
      uses: actions/cache@v5
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Installation des dépendances
      run: pip install -r requirements.txt
    - name: Vérification du schéma classe-dessertes-en-foret et du fichier d'exemple associé
      run: |
        frictionless validate --type schema schema/classe-dessertes-en-foret/schema.json
        frictionless validate --schema schema/classe-dessertes-en-foret/schema.json schema/classe-dessertes-en-foret/exemple-valide.csv
    - name: Vérification du schéma classe-equipement et du fichier d'exemple associé
      run: |
        frictionless validate --type schema schema/classe-equipement/schema.json
        frictionless validate --schema schema/classe-equipement/schema.json schema/classe-equipement/exemple-valide.csv
    - name: Vérification du schéma classe-itineraire-bois-rond et du fichier d'exemple associé
      run: |
        frictionless validate --type schema schema/classe-itineraire-bois-rond /schema.json
        frictionless validate --schema schema/classe-ditineraire-bois-rond /schema.json schema/classe-itineraire-bois-rond /exemple-valide.csv
    - name: Vérification du schéma classe-point-contrainte et du fichier d'exemple associé
      run: |
        frictionless validate --type schema schema/classe-point-contrainte/schema.json
        frictionless validate --schema schema/classe-point-contrainte/schema.json schema/classe-point-contrainte/exemple-valide.csv
    - name: Vérification du schéma classe-ressource-en-eau et du fichier d'exemple associé
      run: |
        frictionless validate --type schema schema/classe-ressource-en-eau/schema.json
        frictionless validate --schema schema/classe-ressource-en-eau/schema.json schema/classe-ressource-en-eau/exemple-valide.csv
    - name: Vérification du schéma classe-troncon-route et du fichier d'exemple associé
      run: |
        frictionless validate --type schema schema/classe-troncon-route/schema.json
        frictionless validate --schema schema/classe-troncon-route/schema.json schema/classe-troncon-route/exemple-valide.csv
    - name: Vérification du datapackage
      run: |
        frictionless validate datapackage.json
